server:
  port: 7001
spring:
  application:
    name: tensquare-eureka
eureka:
  client:
    register-with-eureka: false #是否将自己注册到Eureka服务中，本身就是所有无需
    fetch-registry: false #是否从Eureka中获取注册信息
  instance:
    hostname: 127.0.0.1