server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.93.16:3306/tensquare_recruit?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
  jpa: 
    database: MySQL
    show-sql: true
